'use client';
import {useEffect,useState} from 'react';
const samples=[
 {name:'LUMÉ',kind:'美容室',src:'/samples/lume',note:'光と余白で、サロンの空気まで伝える。'},
 {name:'KASANE',kind:'和菓子ブランド',src:'/samples/kasane',note:'季節をめぐる、静かなブランド体験。'},
 {name:'ATELIER',kind:'設計・クラフト',src:'/samples/atelier',note:'素材の手触りから、仕事の丁寧さを伝える。'}
];
const faq=[['本当に制作料は無料ですか？','はい。今回の先着3名の募集では制作料は0円です。公開後の運用・サポートを月額制にしています。'],['10ページ以上でも無料ですか？','必要な情報量に応じ、10〜20ページ規模にも対応します。構成はヒアリング後に整理します。'],['月額料金は上がりますか？','ご契約期間中は月額2,000円固定です。契約内容を変える場合は、必ず事前にご相談します。'],['修正回数やサーバー代は？','作業内容、ドメイン、サーバーにより条件が異なるため、ご契約前に個別にわかりやすくご案内します。'],['解約時のサイトの扱いは？','データや公開状態を含む条件を、ご契約前に確認いただける形でご案内します。'],['ネットショップも作れますか？','必要な決済・商品管理機能を伺ったうえで、対応可否と追加条件を個別にお伝えします。']];
export default function Home(){
 const[active,setActive]=useState(0);const[progress,setProgress]=useState(0);
 useEffect(()=>{const onScroll=()=>setProgress(Math.min(100,scrollY/(document.documentElement.scrollHeight-innerHeight)*100));addEventListener('scroll',onScroll,{passive:true});const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('seen')),{threshold:.16});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));return()=>{removeEventListener('scroll',onScroll);io.disconnect()}},[]);
 return <main className="new-site">
  <div className="page-progress" style={{width:progress+'%'}}/>
  <header className="new-header"><a className="brand" href="#top"><img src="/leaf-logo.svg" alt="LEAF"/></a><nav><a href="#works">制作例</a><a href="#service">できること</a><a href="#price">料金</a><a href="#faq">FAQ</a></nav><a className="header-cta" href="#contact">制作を相談する</a></header>
  <section className="new-hero" id="top"><div className="hero-image"><img src="/leaf-hero.png" alt="LEAFのWeb制作デスク"/><span className="image-index">01 — DESIGN DESK</span></div><div className="hero-main"><p className="kicker">小さな事業に、ちゃんと伝わるホームページを。</p><h1>ホームページを、<br/><i>もっと気軽に。</i></h1><div className="hero-bottom"><p>見た目だけではなく、何を、誰に、どう伝えるか。<br/>相談しながら、ひとつずつ形にします。</p><a href="#works"><span>制作例を見る</span>↓</a></div></div><div className="hero-ribbon"><span>DESIGN</span><span>RESPONSIVE</span><span>SEO</span><span>UPDATE</span></div></section>
  <section className="intro reveal"><span className="sec-no">01</span><p>派手な言葉よりも、<br/>そのお店らしさが伝わること。</p><h2>写真、言葉、余白、動き。<br/>全部をひとつの体験に。</h2></section>
  <section className="sample-showcase" id="works"><div className="sample-sticky"><div className="browser-frame"><div className="browser-top"><i/><i/><i/><span>leaf / works / {samples[active].name.toLowerCase()}</span><a href={samples[active].src} target="_blank">別ページで開く ↗</a></div><iframe title={samples[active].name+' サンプルサイト'} src={samples[active].src}/></div></div><div className="sample-copy"><p className="eyelabel">実際に触れられる制作サンプル</p><h2>雰囲気だけでなく、<br/>ページとしてつくる。</h2><p className="sample-lead">各サンプルは独立したWebページです。画面の中をスクロールして、写真の見せ方や細かな動きを確かめられます。</p>{samples.map((s,i)=><button key={s.name} className={active===i?'active':''} onClick={()=>setActive(i)}><span>0{i+1}</span><div><small>{s.kind}</small><strong>{s.name}</strong><p>{s.note}</p></div><b>VIEW</b></button>)}</div></section>
  <section className="statement reveal"><img src="/sample-lume.png" alt="自然光が入る美容室"/><div><span className="sec-no">02</span><h2>スクロールするほど、<br/>少しずつ印象が変わる。</h2><p>大きく動かしすぎず、写真がゆっくり現れたり、言葉の位置が少し変わったり。美容室のサイトのような、心地よく続きを見たくなる動きを取り入れます。</p></div></section>
  <section className="service" id="service"><div className="service-head reveal"><span className="sec-no">03</span><h2>つくるところから、<br/>育てるところまで。</h2></div><div className="service-list">{[['01','構成とデザイン','お店や事業の魅力を整理し、必要なページと見せ方を組み立てます。'],['02','スマホ対応','375pxから確認し、どの画面でも読みやすく、押しやすく整えます。'],['03','基本SEOと公開','検索に伝わる基本設定を行い、公開作業まで進めます。'],['04','公開後の修正','文章・写真・サービス内容など、公開後の変化にも相談しながら対応します。']].map(x=><article className="reveal" key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
  <section className="mosaic reveal"><div className="mosaic-a"><img src="/sample-craft.png" alt="紙や陶器などの素材を並べた制作風景"/></div><div className="mosaic-b"><img src="/leaf-studio.png" alt="PCとスマートフォンでサイトを確認する様子"/></div><p>ブランドの空気を伝える写真も、<br/>サイトに合わせて一から用意します。</p></section>
  <section className="new-price" id="price"><div className="price-title reveal"><span className="sec-no">04</span><p>まずは品質を見てほしいから、<br/>価格はここでお伝えします。</p><h2>制作料<span>0</span>円。</h2></div><div className="price-table"><div><small>制作規模</small><strong>10〜20ページ</strong><p>事業に必要な情報量に合わせて設計</p></div><div><small>公開後</small><strong>月額 2,000円</strong><p>ご契約期間中は固定</p></div><div><small>募集</small><strong>先着3名</strong><p>申込状況に応じて手動で更新</p></div></div></section>
  <section className="why reveal"><span className="sec-no">05</span><h2>作ることより、<br/>公開してからを<br/>大切にしたい。</h2><div><p>ホームページは、公開した日が完成ではありません。</p><p>事業が変われば、言葉も写真も、見せ方も変わります。だからLEAFは最初の制作費ではなく、公開後の更新・修正・改善を支える月額制にしました。</p><strong>作って終わりではなく、<br/>一緒に育てていく。</strong></div></section>
  <section className="new-faq" id="faq"><div><span className="sec-no">06</span><h2>よくある<br/>ご質問。</h2><p>未確定の条件を曖昧なまま契約には進めません。</p></div><div>{faq.map((x,i)=><details key={x[0]}><summary><span>0{i+1}</span>{x[0]}<b>＋</b></summary><p>{x[1]}</p></details>)}</div></section>
  <section className="new-cta" id="contact"><div className="cta-leaf">L</div><p>先着3名限定・制作料0円</p><h2>あなたの仕事を、<br/>きちんと伝える場所を。</h2><a href="#contact-note">無料で制作を相談する <span>↗</span></a><small id="contact-note">相談したからといって、契約する必要はありません。お問い合わせ先は公開前に設定します。</small></section>
  <footer><img src="/leaf-logo.svg" alt="LEAF"/><p>ホームページを、もっと気軽に。</p><small>© 2026 LEAF WEB DESIGN</small></footer>
 </main>
}
