'use client';

import { useEffect, useState } from 'react';
const stages=['WIREFRAME','DESIGN','MOBILE','SEO','PUBLISHED'];
const works=[['KASANE','和菓子ブランド','sumi','DESIGN / MOBILE'],['nue','インナーウェア','sand','DESIGN / MOTION'],['KITO','建築・設計','stone','DESIGN / MOBILE'],['NICO','動物病院','sky','MOBILE / SEO'],['LUMÉ','ヘアサロン','rose','DESIGN / MOTION'],['CRAFT COFFEE','コーヒーショップ','coffee','DESIGN / MOBILE']];
const faqs=[['本当に制作料は無料ですか？','はい。今回の先着3名の募集では、ホームページの制作料は0円です。公開後の運用・サポートを月額制にしています。'],['10ページ以上でも無料ですか？','事業内容に必要であれば、10〜20ページ規模にも制作料0円で対応します。ページ構成はヒアリング後に一緒に整理します。'],['月額料金は上がりますか？','ご契約期間中は月額2,000円固定です。契約内容を変更する場合は、必ず事前にご相談します。'],['修正は何回までできますか？','修正の内容や回数の扱いは、作業量を確認して事前にご案内します。まずは希望内容を気軽にご相談ください。'],['ドメイン代・サーバー代は含まれますか？','利用するドメインやサーバーによって条件が異なるため、詳細はヒアリング時にわかりやすくご案内します。'],['解約した場合、サイトはどうなりますか？','データや公開状態の扱いを含め、解約時の条件はご契約前に個別に確認いただける形でご案内します。'],['SEO対策はどこまでですか？','タイトル・説明文・見出し構造・表示速度などの基本SEOを整えます。検索順位を保証するサービスではありません。'],['ネットショップにも対応できますか？','必要な決済・商品管理機能により実現方法が変わります。ご希望を伺い、対応可否と追加条件を個別にお伝えします。']];
function MiniSite({stage=4,name='LEAF'}:{stage?:number;name?:string}){return <div className={`mini-site stage-${stage}`}><div className="mini-nav"><b>{name}</b><span/><span/><span/></div><div className="mini-hero"><div className="mini-copy"><i/><i/><i/></div><div className="mini-photo"/></div><div className="mini-grid"><i/><i/><i/></div></div>}
export default function Home(){const[stage,setStage]=useState(0);const[work,setWork]=useState(0);useEffect(()=>{const timer=setInterval(()=>setStage(s=>(s+1)%stages.length),1500);const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)setWork(Number((e.target as HTMLElement).dataset.index))}),{rootMargin:'-42% 0px -42% 0px'});document.querySelectorAll('[data-index]').forEach(el=>io.observe(el));return()=>{clearInterval(timer);io.disconnect()}},[]);return <main>
<header className="topbar"><a className="logo" href="#top">LEAF<span/></a><nav><a href="#works">制作実績</a><a href="#price">料金</a><a href="#faq">よくある質問</a></nav><a className="top-cta" href="#contact">無料で相談する ↗</a></header>
<section className="hero" id="top"><div className="eyebrow"><span>WEB DESIGN STUDIO</span><span>TOKYO / ONLINE</span></div><div className="hero-copy"><p>事業の顔になる一枚を、丁寧につくる。</p><h1>ホームページを、<br/>もっと気軽に。</h1></div><div className="builder-window"><div className="window-bar"><div className="dots"><i/><i/><i/></div><div className="address">leaf.design / preview</div><div className="live-dot">LIVE PREVIEW</div></div><div className="builder-body"><aside><b>BUILD</b>{stages.map((s,i)=><button key={s} className={stage===i?'active':''} onClick={()=>setStage(i)}><span>0{i+1}</span>{s}</button>)}</aside><div className="canvas"><div className="canvas-label">DESKTOP · 1440</div><MiniSite stage={stage}/>{stage>=2&&<div className="phone"><MiniSite stage={stage}/></div>}</div><div className="inspector"><b>STATUS</b><dl><dt>Viewport</dt><dd>{stage>=2?'Responsive':'Desktop'}</dd><dt>SEO</dt><dd className={stage>=3?'green':''}>{stage>=3?'Ready':'Pending'}</dd><dt>Deploy</dt><dd className={stage>=4?'green':''}>{stage>=4?'Published':'Draft'}</dd></dl></div></div></div><div className="scroll-cue"><span/>SCROLL TO BUILD</div></section>
<section className="quality"><p className="section-num">01 / QUALITY</p><h2>まず、つくれるものを<br/>見てください。</h2><p>価格の前に、品質を。伝わる構成、目に留まるデザイン、スマートフォンでの読みやすさまで、一つずつ設計します。</p></section>
<section className="works" id="works"><div className="works-preview"><div className="portfolio-browser"><div className="window-bar"><div className="dots"><i/><i/><i/></div><div className="address">portfolio / {works[work][0].toLowerCase()}</div></div><div className={`portfolio-screen ${works[work][2]}`}><div className="work-title"><small>{works[work][1]}</small><strong>{works[work][0]}</strong></div><div className="work-image"><span>0{work+1}</span></div></div></div><p className="portfolio-note">※ 現在は制作表現のサンプルです。公開URLを確認できた実績のみ順次リンクします。</p></div><div className="work-list"><p className="section-num">02 / WORKS</p><h2>実際に、こんなサイトを<br/>作っています。</h2>{works.map((w,i)=><article key={w[0]} data-index={i}><span>0{i+1}</span><div><h3>{w[0]}</h3><p>{w[1]}</p><em>{w[3]}</em></div></article>)}</div></section>
<section className="price" id="price"><p className="section-num">03 / PRICE</p><div className="price-head"><h2>そして、<br/>制作料は0円です。</h2><div className="price-change"><span>一般的な制作費</span><del>¥300,000〜</del><strong>¥0</strong></div></div><div className="price-grid"><div><small>PRODUCTION</small><b>制作料</b><strong>0<em>円</em></strong></div><div><small>SUPPORT</small><b>公開後</b><strong>2,000<em>円 / 月</em></strong><p>ご契約期間中は固定</p></div><div className="included"><small>INCLUDED</small><ul><li>10〜20ページ対応可能</li><li>スマートフォン対応</li><li>基本SEO対策</li><li>公開作業</li><li>公開後の修正対応</li></ul></div></div></section>
<section className="reason"><div><p className="section-num">04 / WHY FREE?</p><h2>作ることより、<br/>公開してからを<br/>大切にしたい。</h2></div><div className="reason-copy"><p>ホームページは、公開した日が完成ではありません。</p><p>事業が変われば、伝える言葉も、写真も、サービスの見せ方も変わります。LEAFは最初の制作費ではなく、公開後の更新・修正・改善を支える月額制にしました。</p><p className="lead">作って終わりではなく、<br/>一緒に育てていく。</p></div></section>
<section className="sitemap-section"><div className="sitemap-copy"><p className="section-num">05 / SCALE</p><h2>小さく始めても、<br/>必要な情報は削らない。</h2><div className="page-count"><strong>10–20</strong><span>PAGE<br/>対応可能</span></div><p>無料だから1ページだけ、ではありません。事業をきちんと理解してもらうために必要なページを整理します。</p></div><div className="sitemap"><div className="root-node">HOME</div><div className="branches">{['サービス','料金','会社案内','採用情報','お知らせ','制作実績','スタッフ','ブログ','アクセス','FAQ','お問い合わせ'].map((x,i)=><div key={x} style={{'--i':i} as React.CSSProperties}>{x}</div>)}</div></div></section>
<section className="line-section"><p className="section-num">06 / INCLUDED</p><h2>月額に含まれること。</h2><div className="production-line">{[['01','スマホ対応','PCからスマートフォンまで、画面幅に合わせて自然に組み替わります。','DESKTOP → TABLET → MOBILE'],['02','基本SEO','ページごとのタイトルや説明文、検索に伝わりやすい構造を整えます。','title / description / index'],['03','公開作業','最終確認後、公開までの作業をこちらで進めます。','DEPLOYING → LIVE'],['04','公開後修正','文章や写真の変更など、公開後のご相談にも対応します。','「旧しい」 → 「新しい」']].map(([n,t,d,v])=><article key={n}><div className="line-visual"><span>{v}</span></div><div className="line-copy"><small>{n}</small><h3>{t}</h3><p>{d}</p></div></article>)}</div></section>
<section className="responsive"><div className="responsive-copy"><p className="section-num">07 / RESPONSIVE</p><h2>どの画面でも、<br/>きちんと見やすく。</h2><p>375px・390px・430pxを含むスマートフォン幅でも、文字の大きさ、余白、タップしやすさを確認します。</p></div><div className="device-stage"><div className="desktop-device"><MiniSite/></div><div className="tablet-device"><MiniSite/></div><div className="mobile-device"><MiniSite/></div></div></section>
<section className="after"><div className="published-mark"><span>✓</span>PUBLISHED</div><h2>公開して終わりでは<br/>ありません。</h2><div className="timeline">{[['1 MONTH','文章の修正'],['3 MONTH','写真の変更'],['6 MONTH','サービス追加'],['12 MONTH','ページ更新']].map(([m,x])=><div key={m}><small>{m}</small><i/><strong>{x}</strong></div>)}</div><p>上記は更新の一例です。実際の対応範囲は内容を確認し、事前にご案内します。</p></section>
<section className="flow"><p className="section-num">08 / PROCESS</p><h2>ご相談から、公開まで。</h2><div className="flow-grid">{['お問い合わせ','ヒアリング','構成・デザイン','制作','確認・修正','公開'].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b></div>)}</div><div className="live-message">YOUR WEBSITE IS LIVE.<span/></div></section>
<section className="campaign"><div className="campaign-label">LIMITED OFFER · 3 CLIENTS</div><div className="campaign-main"><div><p>募集枠</p><strong>先着<span>3</span>名</strong><small>申込状況に応じて手動で更新します。</small></div><ul><li><span>制作料</span><b>0円</b></li><li><span>ページ数</span><b>10〜20ページ対応可</b></li><li><span>公開後</span><b>月額2,000円</b></li><li><span>対応</span><b>スマホ・基本SEO・公開後修正</b></li></ul></div></section>
<section className="faq" id="faq"><div><p className="section-num">09 / FAQ</p><h2>よくあるご質問。</h2><p>まだ決まっていないことも、曖昧なまま契約には進みません。気になる点はすべて事前に確認いただけます。</p></div><div>{faqs.map(([q,a],i)=><details key={q}><summary><span>{String(i+1).padStart(2,'0')}</span>{q}<b>＋</b></summary><p>{a}</p></details>)}</div></section>
<section className="desk-photo"><img src="/leaf-studio.png" loading="lazy" alt="パソコンとスマートフォンでWebサイトを確認する制作デスク"/><div><p>DESIGN / BUILD / SUPPORT</p><h2>ひとつずつ、<br/>顔の見える制作を。</h2></div></section>
<section className="final-cta" id="contact"><p>LEAF WEB DESIGN</p><h2>ホームページ、<br/>そろそろ作りませんか。</h2><div className="cta-summary"><span>制作料 0円</span><span>月額 2,000円</span><span>先着3名限定</span></div><a href="#contact-note">無料で制作を相談する <b>↘</b></a><small id="contact-note">相談したからといって、契約する必要はありません。お問い合わせ先は公開前に設定します。</small></section>
<footer><a className="logo" href="#top">LEAF<span/></a><p>ホームページを、もっと気軽に。</p><small>© 2026 LEAF WEB DESIGN</small></footer></main>}
